services:
  - type: web
    name: platica-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: GOOGLE_CALENDAR_API_KEY
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
